# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: compasso1995

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
